name: AnuraFreebuild
main: de.mc_anura.freebuild.AnuraFreebuild
version: 0.2
authors: [LukBukkit, kaenganxt]
depend: [AnuraCore]
api-version: 1.17
commands:
  claim:
    description: Hiermit kannst du dir ein Gebiet claimen
    usage: /<command> [confirm]
